apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuawest-poi-map-app-dev
  annotations:
    argocd/app-name: shuawest-poi-map-app-dev
    backstage.io/kubernetes-id: shuawest-poi-map-app
    backstage.io/kubernetes-namespace: shuawest
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-gh/shuawest-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/dev-pipelines/ns/shuawest/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/k8s/ns/shuawest/deployments/shuawest-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/#https://github.com/rhdh-gh/shuawest-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://shuawest-poi-map-app-shuawest.apps.rosa-x4jc7.l07n.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/shuawest"
  system: workshop-system-shuawest
  consumesApis:
    - gateway-api-shuawest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-shuawest
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/shuawest"
